name: Dependency Review

on:
  schedule:
    - cron: "0 2 * * *"  # Ejecuta diariamente a las 2 AM UTC
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dependency-review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run dependency review
      uses: github/dependency-review-action@v2
